#!/usr/bin/env python3
"""
Minimal Quality Gates runner for CI.

Reads the audit JSON generated by kaike_audit.py and prints a concise
summary that other workflow steps can consume. This script does not
enforce blocking; the workflow step that follows decides pass/fail.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("audit_results.json")
    if not path.exists():
        print(f"Audit file not found: {path}")
        return 0

    try:
        data = json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except Exception as e:
        print(f"Could not parse audit JSON: {e}")
        return 0

    findings = data.get("findings", [])
    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for f in findings:
        sev = (f.get("severity") or "").upper()
        if sev in counts:
            counts[sev] += 1

    print("Quality Audit Summary:")
    print(f"  CRITICAL: {counts['CRITICAL']}")
    print(f"  HIGH:     {counts['HIGH']}")
    print(f"  MEDIUM:   {counts['MEDIUM']}")
    print(f"  LOW:      {counts['LOW']}")

    if findings:
        print("\nTop findings:")
        for f in findings[:5]:
            print(f"  - [{f.get('severity','?')}] {f.get('message','')} ({f.get('file','')})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

